use_frameworks!

platform :ios, '8.0'

target 'HYHUIViewControllerLifeState_Example' do
  pod 'HYHUIViewControllerLifeState', :path => '../'

  target 'HYHUIViewControllerLifeState_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
